sonar.projectKey=bonddim_azure-devops-extensions
sonar.organization=bonddim

# Exclude generated files, test files, and coverage reports from analysis and coverage calculation
sonar.exclusions=**/node_modules/**, **/dist/**, **/out/**, **/coverage/**, **/*.spec.ts, **/*.test.ts
sonar.coverage.exclusions=**/node_modules/**, **/dist/**, **/out/**, **/coverage/**, **/*.spec.ts, **/*.test.ts, **/*.js, **/*.mjs

# Specify the paths to the test execution report and the code coverage report
sonar.testExecutionReportPaths=sonar-report.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info
